### ISSUE TITLE
Disable patchTimestamps by default

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skaled#1317]
Need to disable the next options if they don't exist in the schain config.
```
      contractStorageZeroValuePatchTimestamp: 
      revertableFSPatchTimestamp: 
      contractStoragePatchTimestamp: 
      verifyDaSigsPatchTimestamp
```
